//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdObjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        public int ID { get; set; }
        public int IDInstanceContainer { get; set; }
        public int IDInstanceObject { get; set; }
    
        public virtual ObjectInstance ObjectInstance { get; set; }
        public virtual ObjectInstance ObjectInstance1 { get; set; }
    }
}
