//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdObjects.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEOEntities : DbContext
    {
        public DBEOEntities()
            : base("name=DBEOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Container> Container { get; set; }
        public virtual DbSet<ObjectInstance> ObjectInstance { get; set; }
        public virtual DbSet<ObjectType> ObjectType { get; set; }
        public virtual DbSet<Properties> Properties { get; set; }
        public virtual DbSet<PropertyType> PropertyType { get; set; }
        public virtual DbSet<PropertyValues> PropertyValues { get; set; }
        public virtual DbSet<Version> Version { get; set; }
    
        public virtual ObjectResult<GetInstancesValues_Result> GetInstancesValues(Nullable<int> typeId)
        {
            var typeIdParameter = typeId.HasValue ?
                new ObjectParameter("typeId", typeId) :
                new ObjectParameter("typeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInstancesValues_Result>("GetInstancesValues", typeIdParameter);
        }

        public System.Data.Entity.DbSet<EdObjects.Models.GetInstancesValues_Result> GetInstancesValues_Result { get; set; }
    }
}
