//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdObjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyValues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyValues()
        {
            this.Version = new HashSet<Version>();
        }
    
        public int ID { get; set; }
        public int IDInstanceObject { get; set; }
        public int IDProperty { get; set; }
        public string Value { get; set; }
    
        public virtual ObjectInstance ObjectInstance { get; set; }
        public virtual Properties Properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Version> Version { get; set; }
    }
}
