//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdObjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public int ID { get; set; }
        public int IDParentInstance { get; set; }
        public int IDPropertyValue { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    
        public virtual PropertyValues PropertyValues { get; set; }
        public virtual ObjectInstance ObjectInstance1 { get; set; }
    }
}
